@startuml
skinparam defaultFontSize 16

title Deepin Remote Desktop 模块结构

package "桌面 UI 模块" as pkg_ui {
    component "控制中心"
    component "任务栏"
    component "锁屏"
}

package "lightdm 组件" as pkg_lightdm {
    component "RDP seat管理"
    component "虚拟屏幕管理"
    component "Greeter"
}

package "deepin-remote-desktop 核心" as pkg_drd {
    component "客户端连接管理"
    component "屏幕采集管理"
    component "编码与传输管理"
    component "输入事件管理"
    component "连接安全管理"
    component "服务重定向管理"
    component "远程会话管理"
    component "远程会话权限控制"
    component "配置与隐私管理"
    component "服务端进程管理"
    component "音频管理"
    component "剪切板管理"
    component "网络探测与流量控制"
    component "硬件加速"
    component "外设共享"
}
pkg_ui -[hidden]down- pkg_drd
pkg_lightdm -[hidden]down- pkg_drd

@enduml
